#!/bin/sh

ln -s ~/dotfiles/config/.config/nvim ~/.config/nvim

# Initialize NeoVim & Packer
mkdir -p ~/.local/share/nvim/site/pack/packer/start
ln -s ~/dotfiles/config/.config/nvim/vendor/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
nvim --headless -c 'so ~/dotfiles/config/.config/nvim/lua/gregdodd/packer.lua' -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
